### ISSUE TITLE
The plugin is unable to parse the server-status page on current Apache Version.

### ISSUE THREAD

**Issue by abdullah2993** [bbusschots-nuim/check_apache_serverstatus#2]
Will post the output in a while

**Comment by abdullah2993** [comment]
CRITICAL - failed to access server status page (the content couldn't be parsed at check_apache_serverstatus.pl line 106.
    eval {...} called at check_apache_serverstatus.pl line 109
)

**Comment by woytam** [comment]
There is an error in Perl library Parse::Apache::ServerStatus. On Apache 2.4 in MPM mode, there is a change in output from Apache.
This update works for me:
Find library of Perl, ex. /usr/local/Perl5/Parse/Apache/ServerStatus.pm
and change regex on line 314
from
`<dt>Parent\s+Server\s+Generation:\s+(\d+)</dt>.+?`
to
`<dt>Parent\s+Server\s+MPM\s+Generation:\s+(\d+)</dt>.+?`

Change is the name Parent Server Generation (Apache 2.x) to Parent Server MPM Generation (Apache 2.4). This change will not be backward compatible with Apache 2.2 or less.

The bug has ticket [#119926](https://rt.cpan.org/Public/Bug/Display.html?id=119926)
